export default defineEventHandler(async (event) =>{

    return [
        "H87 - Bucată",
        "KGM - Kilogram",
        "C62 - Unitate ",
        "EA - Unitate",
        "XBX - Cutie",
        "XPA - Pachet",
        "SET - Set",
        "KWH - Kilowatt oră",
        "58 - Kilogram net",
        "LTR - Litru",
        "MON - Lună",
        "MTQ - Metru cub",
        "MWH - Megawatt oră (1000 kW.h)",
        "XCT - Cutie de carton",
        "XBE - Pachet",
        "XZZ - Unitate definită de comun acord",
        "XCQ - Cartuș",
        "XVI - Flacon",
        "MTR - Metru",
        "NIU - Număr de unități internaționale",
        "MTK - Metru pătrat",
        "LM - Metru liniar",
        "PR - Pereche",
        "M4 - Valoare monetară",
        "HUR - Oră",
        "XSX - Set",
        "XUN - Unitate",
        "XGR - Recipient, sticlă",
        "NAR - Număr de articole",
        "GV - Gigajoule",
        "DAY - Zi",
        "XTU - Tub",
        "10 - Grup",
        "XBG - Sac",
        "XPK - Pachet",
        "TNE - Tonă (metrică)",
        "XBO - Sticlă, neprotejată, cilindrică",
        "E48 - Unitate de service",
        "MLT - Mililitru",
        "XPR - Recipient, din plastic",
        "A75 - Tonă de marfă",
        "G48 - Centimetru cub pe oră",
        "XRL - Rolă",
        "NT - Tonă netă",
        "KT - Kit",
        "XSP - Folie de plastic",
        "XSA - Sack",
        "T3 - O mie de bucăți",
        "KMT - Kilometru"
]
})
